[build]
  # Install using legacy peer deps to avoid ERESOLVE conflicts
  # Run the build only; let Netlify Next plugin handle the publish step (supports i18n and modern Next features)
  command = "npm ci --legacy-peer-deps && npm run build"
  # Ensure publish is not the repo root. The Next plugin needs publish != base directory.
  publish = ".netlify"

[build.environment]
  NODE_VERSION = "20.14.0"
  NPM_FLAGS = "--legacy-peer-deps"

[[plugins]]
package = "@netlify/plugin-nextjs"
