[build]
  # Install using legacy peer deps to avoid ERESOLVE conflicts (dangerous-html requires react@17 peer)
  # Use the existing `build` script (next build && next export) to avoid missing-script errors on CI.
  command = "npm ci --legacy-peer-deps && echo 'node:' && node -v && echo 'npm:' && npm -v && npm run build; echo 'build exit code: $?'; echo '--- repo root ---' && pwd && ls -la . && echo '--- out directory ---' && ls -la out || echo 'out missing or ls failed'"
  publish = "out"

[build.environment]
  # Request Node 20 on Netlify
  NODE_VERSION = "20"
  # Also pass npm flags just in case
  NPM_FLAGS = "--legacy-peer-deps"
